#!/usr/bin/env python3
"""Turn any image into the boot splash for the OBD gauge.

Usage:
    python3 tools/make_splash.py path/to/logo.png [--offset 0.0]

Makes a 320x240 image (fills the screen, cropping the long side),
darkens the bottom so the boot text stays readable, and writes
src/splash_img.h. Rebuild and upload afterward.

--offset picks which part survives the crop: 0.0 keeps the top/left,
0.5 the middle, 1.0 the bottom/right. Default 0.0 (keeps heads and logos
near the top of a square image).

Needs Pillow:  pip install pillow
"""
import argparse
import os
from PIL import Image

W, H = 320, 240
FADE_START = 175   # rows below this fade toward the background color
BG = (7, 5, 26)    # matches C_BG in ui.cpp


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image")
    ap.add_argument("--offset", type=float, default=0.0)
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "..", "src", "splash_img.h"))
    ap.add_argument("--preview", help="also save a PNG of the result")
    a = ap.parse_args()

    im = Image.open(a.image).convert("RGB")
    scale = max(W / im.width, H / im.height)
    im = im.resize((round(im.width * scale), round(im.height * scale)), Image.LANCZOS)
    x0 = round((im.width - W) * a.offset)
    y0 = round((im.height - H) * a.offset)
    im = im.crop((x0, y0, x0 + W, y0 + H))

    px = im.load()
    for y in range(FADE_START, H):
        t = ((y - FADE_START) / (H - FADE_START)) ** 1.2 * 0.85
        for x in range(W):
            r, g, b = px[x, y]
            px[x, y] = tuple(round(c * (1 - t) + bc * t) for c, bc in zip((r, g, b), BG))

    if a.preview:
        im.save(a.preview)

    vals = []
    for y in range(H):
        for x in range(W):
            r, g, b = px[x, y]
            vals.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))

    with open(a.out, "w") as f:
        f.write("// Generated by tools/make_splash.py - do not edit by hand\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define SPLASH_W {W}\n#define SPLASH_H {H}\n\n")
        f.write("static const uint16_t SPLASH_IMG[SPLASH_W * SPLASH_H] = {\n")
        for i in range(0, len(vals), 16):
            f.write("  " + ",".join(f"0x{v:04X}" for v in vals[i:i + 16]) + ",\n")
        f.write("};\n")
    print(f"wrote {os.path.normpath(a.out)} ({len(vals) * 2 // 1024} KB of flash)")


if __name__ == "__main__":
    main()
